// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourCompany.DataAccess.DataAccess;

#nullable disable

namespace TourCompany.DataAccess.Migrations
{
    [DbContext(typeof(TourDBContext))]
    [Migration("20260417113438_SeedCork2")]
    partial class SeedCork2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TourCompany.Models.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketAmount")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TourId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TourCompany.Models.Models.BookingExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ExtraId");

                    b.ToTable("BookingExtras");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Picnic",
                            Price = 20.00m,
                            TourId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Picnic",
                            Price = 20.00m,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Audio Guide",
                            Price = 4.00m,
                            TourId = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Pour a Pint",
                            Price = 5.00m,
                            TourId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Bike Rental",
                            Price = 8.00m,
                            TourId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Picnic",
                            Price = 20.00m,
                            TourId = 8
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Picnic",
                            Price = 20.00m,
                            TourId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Map",
                            Price = 2.50m,
                            TourId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Booklet",
                            Price = 1.00m,
                            TourId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Audio Guide",
                            Price = 3.00m,
                            TourId = 9
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Name = "Audio Guide",
                            Price = 3.00m,
                            TourId = 9
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Name = "Wildlife Guide",
                            Price = 6.00m,
                            TourId = 10
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "Waterproof Jacket",
                            Price = 20.00m,
                            TourId = 10
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Name = "Booklet",
                            Price = 5.00m,
                            TourId = 11
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            Name = "Recipe Book",
                            Price = 7.50m,
                            TourId = 12
                        });
                });

            modelBuilder.Entity("TourCompany.Models.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MinCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Discover Glenveagh National Park on a scenic walking tour through rugged mountains, peaceful lakeshores, and native woodland. Follow tranquil paths to Glenveagh Castle, explore beautiful gardens, and experience breathtaking views, rich wildlife, and the park’s unique natural and cultural heritage.",
                            Duration = 120,
                            Image = "\\Images\\Tours\\Glenveagh.jpg",
                            Location = "Donegal",
                            MaxCapacity = 20,
                            MinCapacity = 5,
                            Name = "Glenveagh",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Experience Fanad Lighthouse with a local guide, exploring the peninsula’s history. Learn about lighthouse keepers’ lives, stories of love, loss, and resilience. Discover how light has evolved over centuries with modern technology. Experience an authentic insight into life at this iconic Irish landmark.",
                            Duration = 50,
                            Image = "\\Images\\Tours\\Fanad.jpg",
                            Location = "Donegal",
                            MaxCapacity = 12,
                            MinCapacity = 4,
                            Name = "Fanad Lighthouse",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Join our Sliabh Liag walking tour from the Visitor Centre, exploring stunning cliffs, local culture, and history. Enjoy daily departures, guided insights into language and heritage, and breathtaking scenery, supported by DCC, Fáilte Ireland, and EU funding for an immersive and memorable experience.",
                            Duration = 90,
                            Image = "\\Images\\Tours\\Slieve.jpg",
                            Location = "Donegal",
                            MaxCapacity = 25,
                            MinCapacity = 6,
                            Name = "Slieve League",
                            Price = 17.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Join an intimate Guinness tasting at St. James’s Gate, where a beer specialist guides you through flavors, aromas, and origins. Share stories with the group while exploring iconic Guinness varieties and learn the secrets behind Ireland’s famous brew in a memorable, immersive experience.",
                            Duration = 60,
                            Image = "\\Images\\Tours\\Guinness.jpg",
                            Location = "Dublin",
                            MaxCapacity = 15,
                            MinCapacity = 4,
                            Name = "Guinness",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Explore Kilmainham Gaol and uncover Ireland’s history through the stories of prisoners—from ordinary criminals to freedom fighters. Learn about the 1798 Rebellion, 1916 Easter Rising,  and Civil War, each chapter revealing the struggles and resilience that shaped Ireland’s journey to independence.",
                            Duration = 60,
                            Image = "\\Images\\Tours\\Kilmainham.jpg",
                            Location = "Dublin",
                            MaxCapacity = 28,
                            MinCapacity = 7,
                            Name = "Kilmainham Gaol",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Experience the Titanic story through ten interactive galleries in a self-guided tour. Discover the sights, sounds, and stories of the ship, its passengers, and the city that built her, for the world’s most authentic and immersive retelling of this iconic maritime journey.",
                            Duration = 100,
                            Image = "\\Images\\Tours\\Titanic.jpg",
                            Location = "Antrim",
                            MaxCapacity = 20,
                            MinCapacity = 5,
                            Name = "Titanic Belfast",
                            Price = 27.50m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Embark on a 5-star rated Giant’s Causeway tour from Belfast — travel to this UNESCO World Heritage Site in a luxury, air-conditioned coach, visit stunning coastal locations, explore ancient castles, and uncover myths and legends Belfast has to offer.",
                            Duration = 60,
                            Image = "\\Images\\Tours\\Causeway.jpg",
                            Location = "Antrim",
                            MaxCapacity = 20,
                            MinCapacity = 5,
                            Name = "Giants Causeway",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "At Belfast Zoo you can see more than 1,000 animals over the course of your visit. The zoo is home to more than 130 different species, most of which are currently endangered in the wild. Learn more about the animals by attending a private walking tour.",
                            Duration = 120,
                            Image = "\\Images\\Tours\\BelfastZoo.jpg",
                            Location = "Antrim",
                            MaxCapacity = 5,
                            MinCapacity = 1,
                            Name = "Belfast Zoo",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "See Dublin through a local’s eyes on our walking tour, exploring its history and culture. Visit iconic landmarks like Dublin Castle and Trinity College, hear fascinating stories, and discover hidden gems while experiencing the city’s past and present in a memorable way with a local guide.",
                            Duration = 45,
                            Image = "\\Images\\Tours\\DublinTour.jpg",
                            Location = "Dublin",
                            MaxCapacity = 10,
                            MinCapacity = 5,
                            Name = "Walking Tour",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Join us for a unique experience observing fin, humpback, and minke whales, along with common dolphins, basking sharks, harbour porpoises, sunfish, and other marine wildlife. Enjoy breathtaking scenery as you explore the stunning waters and coastline of Cork, discovering incredible marine life on an unforgettable adventure.",
                            Duration = 60,
                            Image = "\\Images\\Tours\\Whale.jpg",
                            Location = "Cork",
                            MaxCapacity = 30,
                            MinCapacity = 10,
                            Name = "Whale Watching",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Built nearly six hundred years ago by one of Ireland’s greatest chieftains, Cormac MacCarthy, this historic site has attracted attention ever since. Legend says there is a stone that, if kissed, grants eloquence: “Whoever kisses it never misses to grow eloquent.” A fascinating stop on your visiting tour in Ireland.",
                            Duration = 80,
                            Image = "\\Images\\Tours\\Blarney.jpg",
                            Location = "Cork",
                            MaxCapacity = 23,
                            MinCapacity = 8,
                            Name = "Blarney Castle",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Join our food tour led by a local guide as you explore vibrant market stalls filled with fresh seasonal vegetables, poultry, beef, and game like wild Irish rabbit. Enjoy spices, chocolate, coffee bars, and sizzling sausages on the griddle while discovering authentic flavours and stories behind Cork's food culture.",
                            Duration = 70,
                            Image = "\\Images\\Tours\\Market.jpg",
                            Location = "Cork",
                            MaxCapacity = 10,
                            MinCapacity = 6,
                            Name = "The English Market",
                            Price = 22.00m
                        });
                });

            modelBuilder.Entity("TourCompany.Models.Models.Customer", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourCompany.Models.Models.Booking", b =>
                {
                    b.HasOne("TourCompany.Models.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TourCompany.Models.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourCompany.Models.Models.BookingExtra", b =>
                {
                    b.HasOne("TourCompany.Models.Models.Booking", "Booking")
                        .WithMany("BookingExtras")
                        .HasForeignKey("BookingId");

                    b.HasOne("TourCompany.Models.Models.Extra", "Extra")
                        .WithMany("BookingExtra")
                        .HasForeignKey("ExtraId");

                    b.Navigation("Booking");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Extra", b =>
                {
                    b.HasOne("TourCompany.Models.Models.Tour", "Tour")
                        .WithMany("Extras")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Booking", b =>
                {
                    b.Navigation("BookingExtras");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Extra", b =>
                {
                    b.Navigation("BookingExtra");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("TourCompany.Models.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
